#ifndef ACTION_READER_H
#define ACTION_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef EXTRAS_READER_H
#include "Extras_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_Action_table *AllWatchSerialize_Action_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Action_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Action_mutable_vec_t;
#ifndef AllWatchSerialize_Action_identifier
#define AllWatchSerialize_Action_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Action_type_hash ((flatbuffers_thash_t)0x899c121d)
#define AllWatchSerialize_Action_type_identifier "\x1d\x12\x9c\x89"



struct AllWatchSerialize_Action_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Action_vec_len(AllWatchSerialize_Action_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Action_table_t AllWatchSerialize_Action_vec_at(AllWatchSerialize_Action_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Action_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Action)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_Action, temp, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, AllWatchSerialize_Action, a, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(2, AllWatchSerialize_Action, actionName, 0)
__flatbuffers_define_string_field(3, AllWatchSerialize_Action, callback, 0)
__flatbuffers_define_vector_field(4, AllWatchSerialize_Action, extras, AllWatchSerialize_Extras_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* ACTION_READER_H */
