#ifndef APPLICATION_READER_H
#define APPLICATION_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef WIDGET_READER_H
#include "Widget_reader.h"
#endif
#ifndef REQUIREMENTS_READER_H
#include "Requirements_reader.h"
#endif
#ifndef ID_READER_H
#include "Id_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_Application_table *AllWatchSerialize_Application_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Application_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Application_mutable_vec_t;
#ifndef AllWatchSerialize_Application_identifier
#define AllWatchSerialize_Application_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Application_type_hash ((flatbuffers_thash_t)0x198a96bf)
#define AllWatchSerialize_Application_type_identifier "\xbf\x96\x8a\x19"



struct AllWatchSerialize_Application_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Application_vec_len(AllWatchSerialize_Application_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Application_table_t AllWatchSerialize_Application_vec_at(AllWatchSerialize_Application_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Application_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Application)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_Application, reinstall, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_table_field(1, AllWatchSerialize_Application, Id, AllWatchSerialize_Id_table_t, 0)
__flatbuffers_define_vector_field(2, AllWatchSerialize_Application, icon, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(3, AllWatchSerialize_Application, requirements, AllWatchSerialize_Requirements_vec_t, 0)
__flatbuffers_define_vector_field(4, AllWatchSerialize_Application, voicePhrases, flatbuffers_string_vec_t, 0)
__flatbuffers_define_table_field(5, AllWatchSerialize_Application, widget, AllWatchSerialize_Widget_table_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* APPLICATION_READER_H */
