#ifndef BACK_READER_H
#define BACK_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef EXTRAS_READER_H
#include "Extras_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_Back_table *AllWatchSerialize_Back_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Back_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Back_mutable_vec_t;
#ifndef AllWatchSerialize_Back_identifier
#define AllWatchSerialize_Back_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Back_type_hash ((flatbuffers_thash_t)0x3609050)
#define AllWatchSerialize_Back_type_identifier "\x50\x90\x60\x03"



struct AllWatchSerialize_Back_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Back_vec_len(AllWatchSerialize_Back_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Back_table_t AllWatchSerialize_Back_vec_at(AllWatchSerialize_Back_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Back_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Back)

__flatbuffers_define_vector_field(0, AllWatchSerialize_Back, extras, AllWatchSerialize_Extras_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* BACK_READER_H */
