#ifndef CARDATTRIBUTES_READER_H
#define CARDATTRIBUTES_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef ACTION_READER_H
#include "Action_reader.h"
#endif
#ifndef TEMPLATE_READER_H
#include "Template_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_CardAttributes_table *AllWatchSerialize_CardAttributes_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_CardAttributes_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_CardAttributes_mutable_vec_t;
#ifndef AllWatchSerialize_CardAttributes_identifier
#define AllWatchSerialize_CardAttributes_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_CardAttributes_type_hash ((flatbuffers_thash_t)0x53fd77f8)
#define AllWatchSerialize_CardAttributes_type_identifier "\xf8\x77\xfd\x53"



struct AllWatchSerialize_CardAttributes_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_CardAttributes_vec_len(AllWatchSerialize_CardAttributes_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_CardAttributes_table_t AllWatchSerialize_CardAttributes_vec_at(AllWatchSerialize_CardAttributes_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_CardAttributes_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_CardAttributes)

__flatbuffers_define_string_field(0, AllWatchSerialize_CardAttributes, title, 0)
__flatbuffers_define_vector_field(1, AllWatchSerialize_CardAttributes, image, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(2, AllWatchSerialize_CardAttributes, avatar, flatbuffers_uint8_vec_t, 0)
__flatbuffers_define_vector_field(3, AllWatchSerialize_CardAttributes, actions, AllWatchSerialize_Action_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* CARDATTRIBUTES_READER_H */
