#ifndef COMPONENTS_READER_H
#define COMPONENTS_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_ProgressBar_table *AllWatchSerialize_ProgressBar_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_ProgressBar_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_ProgressBar_mutable_vec_t;
typedef const struct AllWatchSerialize_ImageBackground_table *AllWatchSerialize_ImageBackground_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_ImageBackground_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_ImageBackground_mutable_vec_t;
typedef const struct AllWatchSerialize_Component_table *AllWatchSerialize_Component_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Component_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Component_mutable_vec_t;
#ifndef AllWatchSerialize_ProgressBar_identifier
#define AllWatchSerialize_ProgressBar_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_ProgressBar_type_hash ((flatbuffers_thash_t)0xc934bc9d)
#define AllWatchSerialize_ProgressBar_type_identifier "\x9d\xbc\x34\xc9"
#ifndef AllWatchSerialize_ImageBackground_identifier
#define AllWatchSerialize_ImageBackground_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_ImageBackground_type_hash ((flatbuffers_thash_t)0x799c6728)
#define AllWatchSerialize_ImageBackground_type_identifier "\x28\x67\x9c\x79"
#ifndef AllWatchSerialize_Component_identifier
#define AllWatchSerialize_Component_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Component_type_hash ((flatbuffers_thash_t)0xcc524402)
#define AllWatchSerialize_Component_type_identifier "\x02\x44\x52\xcc"



struct AllWatchSerialize_ProgressBar_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_ProgressBar_vec_len(AllWatchSerialize_ProgressBar_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_ProgressBar_table_t AllWatchSerialize_ProgressBar_vec_at(AllWatchSerialize_ProgressBar_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_ProgressBar_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_ProgressBar)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_ProgressBar, progress, flatbuffers_float, float, 0.000000f)

struct AllWatchSerialize_ImageBackground_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_ImageBackground_vec_len(AllWatchSerialize_ImageBackground_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_ImageBackground_table_t AllWatchSerialize_ImageBackground_vec_at(AllWatchSerialize_ImageBackground_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_ImageBackground_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_ImageBackground)

__flatbuffers_define_vector_field(0, AllWatchSerialize_ImageBackground, image, flatbuffers_uint8_vec_t, 0)
typedef uint8_t AllWatchSerialize_Components_union_type_t;
__flatbuffers_define_integer_type(AllWatchSerialize_Components, AllWatchSerialize_Components_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, AllWatchSerialize_Components)
#define AllWatchSerialize_Components_NONE ((AllWatchSerialize_Components_union_type_t)UINT8_C(0))
#define AllWatchSerialize_Components_ProgressBar ((AllWatchSerialize_Components_union_type_t)UINT8_C(1))
#define AllWatchSerialize_Components_ImageBackground ((AllWatchSerialize_Components_union_type_t)UINT8_C(2))

static inline const char *AllWatchSerialize_Components_type_name(AllWatchSerialize_Components_union_type_t type)
{
    switch (type) {
    case AllWatchSerialize_Components_NONE: return "NONE";
    case AllWatchSerialize_Components_ProgressBar: return "ProgressBar";
    case AllWatchSerialize_Components_ImageBackground: return "ImageBackground";
    default: return "";
    }
}

static inline int AllWatchSerialize_Components_is_known_type(AllWatchSerialize_Components_union_type_t type)
{
    switch (type) {
    case AllWatchSerialize_Components_NONE: return 1;
    case AllWatchSerialize_Components_ProgressBar: return 1;
    case AllWatchSerialize_Components_ImageBackground: return 1;
    default: return 0;
    }
}


struct AllWatchSerialize_Component_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Component_vec_len(AllWatchSerialize_Component_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Component_table_t AllWatchSerialize_Component_vec_at(AllWatchSerialize_Component_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Component_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Component)

__flatbuffers_define_union_field(flatbuffers_, 1, AllWatchSerialize_Component, cmp, AllWatchSerialize_Components, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* COMPONENTS_READER_H */
