#ifndef DATABINDING_READER_H
#define DATABINDING_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_PropertyBinding_table *AllWatchSerialize_PropertyBinding_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_PropertyBinding_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_PropertyBinding_mutable_vec_t;
typedef const struct AllWatchSerialize_DataBinding_table *AllWatchSerialize_DataBinding_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_DataBinding_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_DataBinding_mutable_vec_t;
#ifndef AllWatchSerialize_PropertyBinding_identifier
#define AllWatchSerialize_PropertyBinding_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_PropertyBinding_type_hash ((flatbuffers_thash_t)0x3d7ca86b)
#define AllWatchSerialize_PropertyBinding_type_identifier "\x6b\xa8\x7c\x3d"
#ifndef AllWatchSerialize_DataBinding_identifier
#define AllWatchSerialize_DataBinding_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_DataBinding_type_hash ((flatbuffers_thash_t)0xb903b9e0)
#define AllWatchSerialize_DataBinding_type_identifier "\xe0\xb9\x03\xb9"



struct AllWatchSerialize_PropertyBinding_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_PropertyBinding_vec_len(AllWatchSerialize_PropertyBinding_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_PropertyBinding_table_t AllWatchSerialize_PropertyBinding_vec_at(AllWatchSerialize_PropertyBinding_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_PropertyBinding_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_PropertyBinding)

__flatbuffers_define_string_field(0, AllWatchSerialize_PropertyBinding, propertyName, 0)
__flatbuffers_define_string_field(1, AllWatchSerialize_PropertyBinding, value, 0)

struct AllWatchSerialize_DataBinding_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_DataBinding_vec_len(AllWatchSerialize_DataBinding_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_DataBinding_table_t AllWatchSerialize_DataBinding_vec_at(AllWatchSerialize_DataBinding_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_DataBinding_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_DataBinding)

__flatbuffers_define_string_field(0, AllWatchSerialize_DataBinding, id, 0)
__flatbuffers_define_vector_field(1, AllWatchSerialize_DataBinding, bindings, AllWatchSerialize_PropertyBinding_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* DATABINDING_READER_H */
