#ifndef DEFAULTDATATYPES_READER_H
#define DEFAULTDATATYPES_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif



typedef int16_t AllWatchSerialize_DefaultDatatypes_enum_t;
__flatbuffers_define_integer_type(AllWatchSerialize_DefaultDatatypes, AllWatchSerialize_DefaultDatatypes_enum_t, 16)
#define AllWatchSerialize_DefaultDatatypes_Text ((AllWatchSerialize_DefaultDatatypes_enum_t)INT16_C(0))
#define AllWatchSerialize_DefaultDatatypes_Media ((AllWatchSerialize_DefaultDatatypes_enum_t)INT16_C(1))
#define AllWatchSerialize_DefaultDatatypes_List ((AllWatchSerialize_DefaultDatatypes_enum_t)INT16_C(2))
#define AllWatchSerialize_DefaultDatatypes_Map ((AllWatchSerialize_DefaultDatatypes_enum_t)INT16_C(3))
#define AllWatchSerialize_DefaultDatatypes_Messaging ((AllWatchSerialize_DefaultDatatypes_enum_t)INT16_C(4))
#define AllWatchSerialize_DefaultDatatypes_Custom ((AllWatchSerialize_DefaultDatatypes_enum_t)INT16_C(5))

static inline const char *AllWatchSerialize_DefaultDatatypes_name(AllWatchSerialize_DefaultDatatypes_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_DefaultDatatypes_Text: return "Text";
    case AllWatchSerialize_DefaultDatatypes_Media: return "Media";
    case AllWatchSerialize_DefaultDatatypes_List: return "List";
    case AllWatchSerialize_DefaultDatatypes_Map: return "Map";
    case AllWatchSerialize_DefaultDatatypes_Messaging: return "Messaging";
    case AllWatchSerialize_DefaultDatatypes_Custom: return "Custom";
    default: return "";
    }
}

static inline int AllWatchSerialize_DefaultDatatypes_is_known_value(AllWatchSerialize_DefaultDatatypes_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_DefaultDatatypes_Text: return 1;
    case AllWatchSerialize_DefaultDatatypes_Media: return 1;
    case AllWatchSerialize_DefaultDatatypes_List: return 1;
    case AllWatchSerialize_DefaultDatatypes_Map: return 1;
    case AllWatchSerialize_DefaultDatatypes_Messaging: return 1;
    case AllWatchSerialize_DefaultDatatypes_Custom: return 1;
    default: return 0;
    }
}



#include "flatcc/flatcc_epilogue.h"
#endif /* DEFAULTDATATYPES_READER_H */
