#ifndef EXTRAS_READER_H
#define EXTRAS_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_Extras_table *AllWatchSerialize_Extras_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Extras_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Extras_mutable_vec_t;
#ifndef AllWatchSerialize_Extras_identifier
#define AllWatchSerialize_Extras_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Extras_type_hash ((flatbuffers_thash_t)0x5b1b5da8)
#define AllWatchSerialize_Extras_type_identifier "\xa8\x5d\x1b\x5b"



struct AllWatchSerialize_Extras_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Extras_vec_len(AllWatchSerialize_Extras_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Extras_table_t AllWatchSerialize_Extras_vec_at(AllWatchSerialize_Extras_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Extras_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Extras)

__flatbuffers_define_string_field(0, AllWatchSerialize_Extras, key, 0)
__flatbuffers_define_string_field(1, AllWatchSerialize_Extras, value, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* EXTRAS_READER_H */
