#ifndef LISTDATA_READER_H
#define LISTDATA_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef TEMPLATEROOT_READER_H
#include "TemplateRoot_reader.h"
#endif
#ifndef SIMPLELISTENTRY_READER_H
#include "SimpleListEntry_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_ListData_table *AllWatchSerialize_ListData_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_ListData_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_ListData_mutable_vec_t;
#ifndef AllWatchSerialize_ListData_identifier
#define AllWatchSerialize_ListData_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_ListData_type_hash ((flatbuffers_thash_t)0x8a342237)
#define AllWatchSerialize_ListData_type_identifier "\x37\x22\x34\x8a"



struct AllWatchSerialize_ListData_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_ListData_vec_len(AllWatchSerialize_ListData_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_ListData_table_t AllWatchSerialize_ListData_vec_at(AllWatchSerialize_ListData_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_ListData_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_ListData)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_ListData, useCustomTemplate, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_vector_field(1, AllWatchSerialize_ListData, customContent, AllWatchSerialize_Template_vec_t, 0)
__flatbuffers_define_vector_field(2, AllWatchSerialize_ListData, simpleEntries, AllWatchSerialize_SimpleListEntry_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* LISTDATA_READER_H */
