#ifndef MESSAGINGDATA_READER_H
#define MESSAGINGDATA_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef PROFILE_READER_H
#include "Profile_reader.h"
#endif
#ifndef MESSAGE_READER_H
#include "Message_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_MessagingData_table *AllWatchSerialize_MessagingData_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_MessagingData_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_MessagingData_mutable_vec_t;
#ifndef AllWatchSerialize_MessagingData_identifier
#define AllWatchSerialize_MessagingData_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_MessagingData_type_hash ((flatbuffers_thash_t)0x95f10141)
#define AllWatchSerialize_MessagingData_type_identifier "\x41\x01\xf1\x95"



struct AllWatchSerialize_MessagingData_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_MessagingData_vec_len(AllWatchSerialize_MessagingData_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_MessagingData_table_t AllWatchSerialize_MessagingData_vec_at(AllWatchSerialize_MessagingData_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_MessagingData_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_MessagingData)

__flatbuffers_define_vector_field(0, AllWatchSerialize_MessagingData, messages, AllWatchSerialize_Message_vec_t, 0)
__flatbuffers_define_vector_field(1, AllWatchSerialize_MessagingData, profiles, AllWatchSerialize_Profile_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* MESSAGINGDATA_READER_H */
