#ifndef OPEN_READER_H
#define OPEN_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef ID_READER_H
#include "Id_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_Open_table *AllWatchSerialize_Open_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Open_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Open_mutable_vec_t;
#ifndef AllWatchSerialize_Open_identifier
#define AllWatchSerialize_Open_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Open_type_hash ((flatbuffers_thash_t)0x282aca4b)
#define AllWatchSerialize_Open_type_identifier "\x4b\xca\x2a\x28"



struct AllWatchSerialize_Open_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Open_vec_len(AllWatchSerialize_Open_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Open_table_t AllWatchSerialize_Open_vec_at(AllWatchSerialize_Open_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Open_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Open)

__flatbuffers_define_table_field(0, AllWatchSerialize_Open, id, AllWatchSerialize_Id_table_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* OPEN_READER_H */
