#ifndef SHAPEATTRIBUTES_READER_H
#define SHAPEATTRIBUTES_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_ShapeAttributes_table *AllWatchSerialize_ShapeAttributes_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_ShapeAttributes_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_ShapeAttributes_mutable_vec_t;
#ifndef AllWatchSerialize_ShapeAttributes_identifier
#define AllWatchSerialize_ShapeAttributes_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_ShapeAttributes_type_hash ((flatbuffers_thash_t)0x1a7d05f9)
#define AllWatchSerialize_ShapeAttributes_type_identifier "\xf9\x05\x7d\x1a"

typedef int16_t AllWatchSerialize_Shape_enum_t;
__flatbuffers_define_integer_type(AllWatchSerialize_Shape, AllWatchSerialize_Shape_enum_t, 16)
#define AllWatchSerialize_Shape_Ellipse ((AllWatchSerialize_Shape_enum_t)INT16_C(0))
#define AllWatchSerialize_Shape_Rectangle ((AllWatchSerialize_Shape_enum_t)INT16_C(1))

static inline const char *AllWatchSerialize_Shape_name(AllWatchSerialize_Shape_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_Shape_Ellipse: return "Ellipse";
    case AllWatchSerialize_Shape_Rectangle: return "Rectangle";
    default: return "";
    }
}

static inline int AllWatchSerialize_Shape_is_known_value(AllWatchSerialize_Shape_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_Shape_Ellipse: return 1;
    case AllWatchSerialize_Shape_Rectangle: return 1;
    default: return 0;
    }
}



struct AllWatchSerialize_ShapeAttributes_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_ShapeAttributes_vec_len(AllWatchSerialize_ShapeAttributes_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_ShapeAttributes_table_t AllWatchSerialize_ShapeAttributes_vec_at(AllWatchSerialize_ShapeAttributes_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_ShapeAttributes_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_ShapeAttributes)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_ShapeAttributes, type, AllWatchSerialize_Shape, AllWatchSerialize_Shape_enum_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, AllWatchSerialize_ShapeAttributes, fill, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))

#include "flatcc/flatcc_epilogue.h"
#endif /* SHAPEATTRIBUTES_READER_H */
