#ifndef SIMPLELISTENTRY_READER_H
#define SIMPLELISTENTRY_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef ACTION_READER_H
#include "Action_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_SimpleListEntry_table *AllWatchSerialize_SimpleListEntry_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_SimpleListEntry_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_SimpleListEntry_mutable_vec_t;
#ifndef AllWatchSerialize_SimpleListEntry_identifier
#define AllWatchSerialize_SimpleListEntry_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_SimpleListEntry_type_hash ((flatbuffers_thash_t)0x420b50d7)
#define AllWatchSerialize_SimpleListEntry_type_identifier "\xd7\x50\x0b\x42"

typedef int16_t AllWatchSerialize_Layout_enum_t;
__flatbuffers_define_integer_type(AllWatchSerialize_Layout, AllWatchSerialize_Layout_enum_t, 16)
#define AllWatchSerialize_Layout_Text ((AllWatchSerialize_Layout_enum_t)INT16_C(0))
#define AllWatchSerialize_Layout_MultilineText ((AllWatchSerialize_Layout_enum_t)INT16_C(1))
#define AllWatchSerialize_Layout_WithIcon ((AllWatchSerialize_Layout_enum_t)INT16_C(2))
#define AllWatchSerialize_Layout_Menu ((AllWatchSerialize_Layout_enum_t)INT16_C(3))

static inline const char *AllWatchSerialize_Layout_name(AllWatchSerialize_Layout_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_Layout_Text: return "Text";
    case AllWatchSerialize_Layout_MultilineText: return "MultilineText";
    case AllWatchSerialize_Layout_WithIcon: return "WithIcon";
    case AllWatchSerialize_Layout_Menu: return "Menu";
    default: return "";
    }
}

static inline int AllWatchSerialize_Layout_is_known_value(AllWatchSerialize_Layout_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_Layout_Text: return 1;
    case AllWatchSerialize_Layout_MultilineText: return 1;
    case AllWatchSerialize_Layout_WithIcon: return 1;
    case AllWatchSerialize_Layout_Menu: return 1;
    default: return 0;
    }
}



struct AllWatchSerialize_SimpleListEntry_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_SimpleListEntry_vec_len(AllWatchSerialize_SimpleListEntry_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_SimpleListEntry_table_t AllWatchSerialize_SimpleListEntry_vec_at(AllWatchSerialize_SimpleListEntry_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_SimpleListEntry_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_SimpleListEntry)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_SimpleListEntry, layout, AllWatchSerialize_Layout, AllWatchSerialize_Layout_enum_t, INT16_C(0))
__flatbuffers_define_table_field(1, AllWatchSerialize_SimpleListEntry, mainAction, AllWatchSerialize_Action_table_t, 0)
__flatbuffers_define_vector_field(2, AllWatchSerialize_SimpleListEntry, sideActions, AllWatchSerialize_Action_vec_t, 0)
__flatbuffers_define_vector_field(3, AllWatchSerialize_SimpleListEntry, lines, flatbuffers_string_vec_t, 0)
__flatbuffers_define_vector_field(4, AllWatchSerialize_SimpleListEntry, icon, flatbuffers_uint8_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* SIMPLELISTENTRY_READER_H */
