#ifndef STYLE_READER_H
#define STYLE_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef BACKGROUND_READER_H
#include "Background_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_Style_table *AllWatchSerialize_Style_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Style_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Style_mutable_vec_t;
#ifndef AllWatchSerialize_Style_identifier
#define AllWatchSerialize_Style_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Style_type_hash ((flatbuffers_thash_t)0xedf8dd8)
#define AllWatchSerialize_Style_type_identifier "\xd8\x8d\xdf\x0e"



struct AllWatchSerialize_Style_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Style_vec_len(AllWatchSerialize_Style_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Style_table_t AllWatchSerialize_Style_vec_at(AllWatchSerialize_Style_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Style_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Style)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_Style, absoluteWidth, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, AllWatchSerialize_Style, absoluteHeight, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(2, AllWatchSerialize_Style, backgroundColor, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(3, AllWatchSerialize_Style, borderColor, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_table_field(4, AllWatchSerialize_Style, background, AllWatchSerialize_Background_table_t, 0)
__flatbuffers_define_scalar_field(5, AllWatchSerialize_Style, x, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(6, AllWatchSerialize_Style, y, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(7, AllWatchSerialize_Style, marginTop, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(8, AllWatchSerialize_Style, marginBottom, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(9, AllWatchSerialize_Style, marginLeft, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(10, AllWatchSerialize_Style, marginRight, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(11, AllWatchSerialize_Style, width, flatbuffers_double, double, 0.000000)
__flatbuffers_define_scalar_field(12, AllWatchSerialize_Style, height, flatbuffers_double, double, 0.000000)
__flatbuffers_define_scalar_field(13, AllWatchSerialize_Style, offsetX, flatbuffers_double, double, 0.000000)
__flatbuffers_define_scalar_field(14, AllWatchSerialize_Style, offsetY, flatbuffers_double, double, 0.000000)

#include "flatcc/flatcc_epilogue.h"
#endif /* STYLE_READER_H */
