#ifndef TEXTDATA_READER_H
#define TEXTDATA_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef COMPONENTS_READER_H
#include "Components_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_TextData_table *AllWatchSerialize_TextData_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_TextData_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_TextData_mutable_vec_t;
#ifndef AllWatchSerialize_TextData_identifier
#define AllWatchSerialize_TextData_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_TextData_type_hash ((flatbuffers_thash_t)0xc9bca268)
#define AllWatchSerialize_TextData_type_identifier "\x68\xa2\xbc\xc9"



struct AllWatchSerialize_TextData_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_TextData_vec_len(AllWatchSerialize_TextData_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_TextData_table_t AllWatchSerialize_TextData_vec_at(AllWatchSerialize_TextData_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_TextData_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_TextData)

__flatbuffers_define_string_field(0, AllWatchSerialize_TextData, major, 0)
__flatbuffers_define_string_field(1, AllWatchSerialize_TextData, minor, 0)
__flatbuffers_define_vector_field(2, AllWatchSerialize_TextData, additionalComponents, AllWatchSerialize_Component_vec_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* TEXTDATA_READER_H */
