#ifndef TEXTATTRIBUTES_READER_H
#define TEXTATTRIBUTES_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_TextAttributes_table *AllWatchSerialize_TextAttributes_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_TextAttributes_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_TextAttributes_mutable_vec_t;
#ifndef AllWatchSerialize_TextAttributes_identifier
#define AllWatchSerialize_TextAttributes_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_TextAttributes_type_hash ((flatbuffers_thash_t)0x46c4b2a9)
#define AllWatchSerialize_TextAttributes_type_identifier "\xa9\xb2\xc4\x46"



struct AllWatchSerialize_TextAttributes_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_TextAttributes_vec_len(AllWatchSerialize_TextAttributes_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_TextAttributes_table_t AllWatchSerialize_TextAttributes_vec_at(AllWatchSerialize_TextAttributes_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_TextAttributes_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_TextAttributes)

__flatbuffers_define_scalar_field(0, AllWatchSerialize_TextAttributes, fontSize, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(1, AllWatchSerialize_TextAttributes, fontFamily, 0)
__flatbuffers_define_string_field(2, AllWatchSerialize_TextAttributes, text, 0)
__flatbuffers_define_scalar_field(3, AllWatchSerialize_TextAttributes, color, flatbuffers_int32, int32_t, INT32_C(0))

#include "flatcc/flatcc_epilogue.h"
#endif /* TEXTATTRIBUTES_READER_H */
