#ifndef UPDATE_READER_H
#define UPDATE_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef VIEW_READER_H
#include "View_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_Update_table *AllWatchSerialize_Update_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_Update_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_Update_mutable_vec_t;
#ifndef AllWatchSerialize_Update_identifier
#define AllWatchSerialize_Update_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_Update_type_hash ((flatbuffers_thash_t)0x5a66b856)
#define AllWatchSerialize_Update_type_identifier "\x56\xb8\x66\x5a"



struct AllWatchSerialize_Update_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_Update_vec_len(AllWatchSerialize_Update_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_Update_table_t AllWatchSerialize_Update_vec_at(AllWatchSerialize_Update_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_Update_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_Update)

__flatbuffers_define_table_field(0, AllWatchSerialize_Update, view, AllWatchSerialize_View_table_t, 0)

#include "flatcc/flatcc_epilogue.h"
#endif /* UPDATE_READER_H */
