#ifndef VIEW_READER_H
#define VIEW_READER_H

/* Generated by flatcc 0.5.2 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#ifndef MESSAGINGDATA_READER_H
#include "MessagingData_reader.h"
#endif
#ifndef LISTDATA_READER_H
#include "ListData_reader.h"
#endif
#ifndef TEXTDATA_READER_H
#include "TextData_reader.h"
#endif
#ifndef ACTION_READER_H
#include "Action_reader.h"
#endif
#ifndef DEFAULTDATATYPES_READER_H
#include "DefaultDatatypes_reader.h"
#endif
#ifndef TEMPLATEROOT_READER_H
#include "TemplateRoot_reader.h"
#endif
#ifndef ID_READER_H
#include "Id_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct AllWatchSerialize_View_table *AllWatchSerialize_View_table_t;
typedef const flatbuffers_uoffset_t *AllWatchSerialize_View_vec_t;
typedef flatbuffers_uoffset_t *AllWatchSerialize_View_mutable_vec_t;
#ifndef AllWatchSerialize_View_identifier
#define AllWatchSerialize_View_identifier flatbuffers_identifier
#endif
#define AllWatchSerialize_View_type_hash ((flatbuffers_thash_t)0x10a39382)
#define AllWatchSerialize_View_type_identifier "\x82\x93\xa3\x10"

typedef int16_t AllWatchSerialize_DefaultStyle_enum_t;
__flatbuffers_define_integer_type(AllWatchSerialize_DefaultStyle, AllWatchSerialize_DefaultStyle_enum_t, 16)
#define AllWatchSerialize_DefaultStyle_Notification ((AllWatchSerialize_DefaultStyle_enum_t)INT16_C(0))
#define AllWatchSerialize_DefaultStyle_TextWall ((AllWatchSerialize_DefaultStyle_enum_t)INT16_C(1))
#define AllWatchSerialize_DefaultStyle_ToBottom ((AllWatchSerialize_DefaultStyle_enum_t)INT16_C(2))
#define AllWatchSerialize_DefaultStyle_ToTop ((AllWatchSerialize_DefaultStyle_enum_t)INT16_C(3))
#define AllWatchSerialize_DefaultStyle_Center ((AllWatchSerialize_DefaultStyle_enum_t)INT16_C(4))

static inline const char *AllWatchSerialize_DefaultStyle_name(AllWatchSerialize_DefaultStyle_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_DefaultStyle_Notification: return "Notification";
    case AllWatchSerialize_DefaultStyle_TextWall: return "TextWall";
    case AllWatchSerialize_DefaultStyle_ToBottom: return "ToBottom";
    case AllWatchSerialize_DefaultStyle_ToTop: return "ToTop";
    case AllWatchSerialize_DefaultStyle_Center: return "Center";
    default: return "";
    }
}

static inline int AllWatchSerialize_DefaultStyle_is_known_value(AllWatchSerialize_DefaultStyle_enum_t value)
{
    switch (value) {
    case AllWatchSerialize_DefaultStyle_Notification: return 1;
    case AllWatchSerialize_DefaultStyle_TextWall: return 1;
    case AllWatchSerialize_DefaultStyle_ToBottom: return 1;
    case AllWatchSerialize_DefaultStyle_ToTop: return 1;
    case AllWatchSerialize_DefaultStyle_Center: return 1;
    default: return 0;
    }
}


typedef uint8_t AllWatchSerialize_ViewData_union_type_t;
__flatbuffers_define_integer_type(AllWatchSerialize_ViewData, AllWatchSerialize_ViewData_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, AllWatchSerialize_ViewData)
#define AllWatchSerialize_ViewData_NONE ((AllWatchSerialize_ViewData_union_type_t)UINT8_C(0))
#define AllWatchSerialize_ViewData_TextData ((AllWatchSerialize_ViewData_union_type_t)UINT8_C(1))
#define AllWatchSerialize_ViewData_ListData ((AllWatchSerialize_ViewData_union_type_t)UINT8_C(2))
#define AllWatchSerialize_ViewData_MessagingData ((AllWatchSerialize_ViewData_union_type_t)UINT8_C(3))

static inline const char *AllWatchSerialize_ViewData_type_name(AllWatchSerialize_ViewData_union_type_t type)
{
    switch (type) {
    case AllWatchSerialize_ViewData_NONE: return "NONE";
    case AllWatchSerialize_ViewData_TextData: return "TextData";
    case AllWatchSerialize_ViewData_ListData: return "ListData";
    case AllWatchSerialize_ViewData_MessagingData: return "MessagingData";
    default: return "";
    }
}

static inline int AllWatchSerialize_ViewData_is_known_type(AllWatchSerialize_ViewData_union_type_t type)
{
    switch (type) {
    case AllWatchSerialize_ViewData_NONE: return 1;
    case AllWatchSerialize_ViewData_TextData: return 1;
    case AllWatchSerialize_ViewData_ListData: return 1;
    case AllWatchSerialize_ViewData_MessagingData: return 1;
    default: return 0;
    }
}


struct AllWatchSerialize_View_table { uint8_t unused__; };

static inline size_t AllWatchSerialize_View_vec_len(AllWatchSerialize_View_vec_t vec)
__flatbuffers_vec_len(vec)
static inline AllWatchSerialize_View_table_t AllWatchSerialize_View_vec_at(AllWatchSerialize_View_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(AllWatchSerialize_View_table_t, vec, i, 0)
__flatbuffers_table_as_root(AllWatchSerialize_View)

__flatbuffers_define_table_field(0, AllWatchSerialize_View, id, AllWatchSerialize_Id_table_t, 0)
__flatbuffers_define_string_field(1, AllWatchSerialize_View, name, 0)
__flatbuffers_define_scalar_field(2, AllWatchSerialize_View, datatype, AllWatchSerialize_DefaultDatatypes, AllWatchSerialize_DefaultDatatypes_enum_t, INT16_C(0))
__flatbuffers_define_scalar_field(3, AllWatchSerialize_View, usesTemplate, flatbuffers_bool, flatbuffers_bool_t, UINT8_C(0))
__flatbuffers_define_table_field(4, AllWatchSerialize_View, template, AllWatchSerialize_TemplateRoot_table_t, 0)
__flatbuffers_define_union_field(flatbuffers_, 6, AllWatchSerialize_View, data, AllWatchSerialize_ViewData, 0)
__flatbuffers_define_vector_field(7, AllWatchSerialize_View, actions, AllWatchSerialize_Action_vec_t, 0)
__flatbuffers_define_scalar_field(8, AllWatchSerialize_View, defaultStyle, AllWatchSerialize_DefaultStyle, AllWatchSerialize_DefaultStyle_enum_t, INT16_C(0))

#include "flatcc/flatcc_epilogue.h"
#endif /* VIEW_READER_H */
